[package]
name = "ta_c"
version = "0.1.0"
authors = ["fedormatantsev <fedormatantsev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ta = { path="../ta" }

[lib]
crate-type=["dylib"]
